In [1]:
import numpy as np
import pandas as pd

# for display
import warnings
warnings.filterwarnings('ignore')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"  #default 'last_expr'

# Introduction to Modeling Libraries 

## Interfacing Between Pandas and Modeling Code

### DataFrame -> Numpy Arrays

In [14]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.],
    's': list('abcde')})
data
data.columns
data.values

x0    x1    y  s
0   1  0.01 -1.5  a
1   2 -0.01  0.0  b
2   3  0.25  3.6  c
3   4 -4.10  1.3  d
4   5  0.00 -2.0  e

Index(['x0', 'x1', 'y', 's'], dtype='object')

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

### Numpy Arrays -> DataFrame

In [11]:
df2 = pd.DataFrame(data.values, columns=['x0', 'x1', 'y', 's'])
df2

x0    x1    y  s
0  1  0.01 -1.5  a
1  2 -0.01    0  b
2  3  0.25  3.6  c
3  4  -4.1  1.3  d
4  5     0   -2  e

In [15]:
data['s'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                  categories=['a', 'b'])
data

x0    x1    y  s
0   1  0.01 -1.5  a
1   2 -0.01  0.0  b
2   3  0.25  3.6  a
3   4 -4.10  1.3  a
4   5  0.00 -2.0  b

In [24]:
pd.get_dummies(data, prefix='s')

x0    x1    y  s_a  s_b
0   1  0.01 -1.5    1    0
1   2 -0.01  0.0    0    1
2   3  0.25  3.6    1    0
3   4 -4.10  1.3    1    0
4   5  0.00 -2.0    0    1

## Creating Model Descriptions with Patsy

y ~ x0 + x1

In [2]:
import patsy

data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})
data

y, X = patsy.dmatrices("y ~ x0 + x1", data)

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [3]:
y
X

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [4]:
np.asarray(y)
np.asarray(X)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

Suppress the 'Intercept' term

In [5]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [14]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

In [16]:
coef
coef.squeeze()

coef.shape, coef.squeeze().shape

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

array([ 0.31290976, -0.07910564, -0.26546384])

((3, 1), (3,))

In [17]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

### Data Transformations in Patsy Formulas

#### Mixing Python code into the formula

In [19]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

#### Patsy's built-in functions

In [20]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

How to add two columns literally

In [21]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

#### How to reuse the previous design matrices for the same transformation
This is convenient to apply the same operation to a validation set during model training.

In [18]:
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'y': [1, 2, 3, 4]})
new_X = patsy.build_design_matrices([X.design_info], new_data)
new_X

[DesignMatrix with shape (4, 3)
   Intercept  x0    x1
           1   6   3.1
           1   7  -0.5
           1   8   0.0
           1   9   2.3
   Terms:
     'Intercept' (column 0)
     'x0' (column 1)
     'x1' (column 2)]

### Categorical Data and Patsy

In [24]:
data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1': [1, 2, 3, 4, 5, 6, 7, 8],
    'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})
y, X = patsy.dmatrices('v2 ~ key1', data)
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

#### Keep both levels of the dummy variable if there is no intercept in the model

In [25]:
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

#### Convert a numerical column to a categorical one

In [26]:
y, X = patsy.dmatrices('v2 ~ C(key2)', data)
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

#### Add interaction term b/t two categorical variables

In [27]:
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})
data
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)
X
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)
X

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

## Introduction to statsmodels

### Multiple Linear Regression

In [47]:
# two interfaces: array-based & formula-based
import statsmodels.api as sm
import statsmodels.formula.api as smf

#### Use Numpy Arrays

In [49]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,  # convert int to a tuple
    return mean + np.sqrt(variance) * np.random.randn(*size)

np.random.seed(12345)

In [50]:
# create Y/X data for multiple linear regression
N = 100
X = np.c_[dnorm(0, 0.4, size=N),  # c_: column stack, note np.c_[], not ()
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]

eps  = dnorm(0, 0.1, size=N) # irreducible error
beta = [0.1, 0.3, 0.5]       # coefficients of true f()

y = np.dot(X, beta) + 2 + 0.5*eps
X.shape, y.shape

X[:2]
X = sm.add_constant(X) # add an interception term
X[:2]

results = sm.OLS(y, X).fit()
results.params
print(results.summary())

((100, 3), (100,))

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986]])

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986]])

array([2.01677928, 0.13807436, 0.26241298, 0.50740397])

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.761
Model:                            OLS   Adj. R-squared:                  0.753
Method:                 Least Squares   F-statistic:                     101.8
Date:                Fri, 10 Apr 2020   Prob (F-statistic):           1.04e-29
Time:                        15:33:12   Log-Likelihood:                 35.480
No. Observations:                 100   AIC:                            -62.96
Df Residuals:                      96   BIC:                            -52.54
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.0168      0.018    114.448      0.0

#### Use Formulas

In [51]:
# Patsy formulas + Pandas obj
data = pd.DataFrame(X[:,1:4], columns=['col0', 'col1', 'col2'])
data['y'] = y
data[:5]

results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()
results.params
results.tvalues

results.predict(data[:5])

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  2.151602
1  0.302910 -0.435742 -0.254180  1.549499
2 -0.328522 -0.025302  0.138351  1.968928
3 -0.351475 -0.719605 -0.258215  1.565185
4  1.243269 -0.373799 -0.522629  1.810966

Intercept    2.016779
col0         0.138074
col1         0.262413
col2         0.507404
dtype: float64

Intercept    114.447930
col0           5.204386
col1          11.323376
col2          12.426615
dtype: float64

0    1.936507
1    1.815287
2    2.034979
3    1.648397
4    1.825169
dtype: float64

### Estimating Time Series Processes

In [55]:
init_x = 4

import random
values = [init_x, init_x]
N = 1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [56]:
MAXLAGS = 5
model = sm.tsa.AR(values)
results = model.fit(MAXLAGS)

In [57]:
results.params

array([ 0.00791554,  0.71074082, -0.31689896, -0.06724519,  0.0041215 ,
       -0.00079061])

## Introduction to scikit-learn

In [58]:
train = pd.read_csv('datasets/titanic/train.csv')
test = pd.read_csv('datasets/titanic/test.csv')
train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [59]:
train.isnull().sum()
test.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [60]:
impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

In [61]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [62]:
predictors = ['Pclass', 'IsFemale', 'Age']
X_train = train[predictors].values
X_test = test[predictors].values
y_train = train['Survived'].values
X_train[:5]
y_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

array([0, 1, 1, 1, 0])

In [63]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [64]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [65]:
y_predict = model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

(y_true == y_predict).mean()

In [66]:
from sklearn.linear_model import LogisticRegressionCV
model_cv = LogisticRegressionCV(10)
model_cv.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv='warn', dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='warn', n_jobs=None, penalty='l2',
           random_state=None, refit=True, scoring=None, solver='lbfgs',
           tol=0.0001, verbose=0)

In [67]:
from sklearn.model_selection import cross_val_score
model = LogisticRegression(C=10)
scores = cross_val_score(model, X_train, y_train, cv=4)
scores

array([0.77232143, 0.80269058, 0.77027027, 0.78828829])